# Generated by Django 4.1.13 on 2024-06-09 13:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_record",
                    models.DateField(
                        verbose_name=datetime.datetime(
                            2024, 6, 9, 13, 3, 22, 305797, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("total", models.FloatField(default=0.0)),
                (
                    "items_list",
                    models.ManyToManyField(related_name="itemsOrder", to="items.items"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userOrder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
