# Generated by Django 4.1.13 on 2024-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="tech",
                        max_length=20,
                        verbose_name=[
                            ("phone", "PHONE"),
                            ("shirt", "SHIRT"),
                            ("pant", "PANT"),
                            ("tech", "TECH"),
                        ],
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(related_name="catItems", to="items.items"),
                ),
            ],
        ),
    ]
