# Generated by Django 4.1.13 on 2024-05-27 14:32

import apps.users.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(default="", max_length=254, unique=True)),
                ("name", models.CharField(default="user", max_length=255)),
                (
                    "role",
                    models.CharField(
                        default="buyer",
                        max_length=15,
                        verbose_name=[
                            ("admin", "ADMIN"),
                            ("shop", "SHOP"),
                            ("buyer", "BUYER"),
                        ],
                    ),
                ),
                ("date_of_birth", models.DateTimeField()),
                ("reset_code", models.CharField(max_length=10, null=True)),
                ("reset_code_exp", models.DateTimeField(null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "last_login",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            5,
                            27,
                            14,
                            32,
                            14,
                            979090,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
            },
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
    ]
