# Generated by Django 4.1.13 on 2024-05-27 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 27, 14, 34, 13, 828, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
