# Generated by Django 4.1.13 on 2024-06-07 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 7, 9, 50, 25, 58996, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
