# Generated by Django 4.1.13 on 2024-06-07 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 7, 12, 59, 37, 487196, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
