# Generated by Django 4.1.13 on 2024-06-09 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 9, 13, 3, 22, 293827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
